[#709] Implementing LDevID generation
nsacyber/HIRS pull request #814
Opened 2024-07-22 13:22 UTC by iadgovuser59

This code implements generating an LDevID certificate (bound to a device's TPM) via the combined actions of both the provisioner and HIRS portal. Additionally, a new column is visible under the portal's Issued Certificates page, in addition to the generation option for LDevIDs visible under the policy page.

Closes several tickets: #709, #738, #739, and #740.

2024-08-14 14:17 UTC, iadgovuser29 requested changes

2024-08-14 14:17 UTC, iadgovuser29 commented on HIRS_Provisioner.NET/hirs/appsettings.json
> +  "cert_prefix": "",
This cert_prefix option is confusing. efi_prefix is looking for the root of the EFI system partition. cert_prefix is looking for the exact directory to place files we generate. Consider renaming cert_prefix to better fit the value being requested. Example: certificate_output_directory

2024-08-19 17:28 UTC, iadgovuser26 approved these changes

2024-08-19 18:29 UTC, iadgovuser29 approved these changes

2024-08-19 18:39 UTC, merged